version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: civicpulse_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: civicpulse
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
